services:
  # Frontend - Next.js Container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    mem_limit: 2g

  # Backend - FastAPI Container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
      - VISION_SERVICE_URL=http://vision-service:8001
    depends_on:
      - vision-service
    restart: unless-stopped
    mem_limit: 1g

  # Vision Service - ML Model Container
  vision-service:
    build:
      context: ./vision-service
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    volumes:
      - ./vision-service/app:/app/app
      - ./vision-service/data:/app/data
      - ./vision-service/models:/app/models
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
    mem_limit: 4g

volumes:
  node_modules:
  next_build:
